const TOP_CITIES = [
  // Africa
  { name: "Lagos", country: "NG", continent: "Africa" },
  { name: "Cairo", country: "EG", continent: "Africa" },
  { name: "Kinshasa", country: "CD", continent: "Africa" },
  { name: "Luanda", country: "AO", continent: "Africa" },
  { name: "Johannesburg", country: "ZA", continent: "Africa" },
  { name: "Nairobi", country: "KE", continent: "Africa" },
  { name: "Casablanca", country: "MA", continent: "Africa" },
  { name: "Addis Ababa", country: "ET", continent: "Africa" },
  { name: "Abidjan", country: "CI", continent: "Africa" },
  { name: "Algiers", country: "DZ", continent: "Africa" },
  // Asia
  { name: "Tokyo", country: "JP", continent: "Asia" },
  { name: "Delhi", country: "IN", continent: "Asia" },
  { name: "Shanghai", country: "CN", continent: "Asia" },
  { name: "Mumbai", country: "IN", continent: "Asia" },
  { name: "Dhaka", country: "BD", continent: "Asia" },
  { name: "Jakarta", country: "ID", continent: "Asia" },
  { name: "Seoul", country: "KR", continent: "Asia" },
  { name: "Bangkok", country: "TH", continent: "Asia" },
  { name: "Manila", country: "PH", continent: "Asia" },
  { name: "Riyadh", country: "SA", continent: "Asia" },
  { name: "Singapore", country: "SG", continent: "Asia" },
  { name: "Kuala Lumpur", country: "MY", continent: "Asia" },
  { name: "Tehran", country: "IR", continent: "Asia" },
  { name: "Karachi", country: "PK", continent: "Asia" },
  { name: "Beijing", country: "CN", continent: "Asia" },
  { name: "Hong Kong", country: "HK", continent: "Asia" },
  // Europe
  { name: "Moscow", country: "RU", continent: "Europe" },
  { name: "London", country: "GB", continent: "Europe" },
  { name: "Paris", country: "FR", continent: "Europe" },
  { name: "Istanbul", country: "TR", continent: "Europe" },
  { name: "Madrid", country: "ES", continent: "Europe" },
  { name: "Berlin", country: "DE", continent: "Europe" },
  { name: "Rome", country: "IT", continent: "Europe" },
  { name: "Vienna", country: "AT", continent: "Europe" },
  { name: "Warsaw", country: "PL", continent: "Europe" },
  { name: "Budapest", country: "HU", continent: "Europe" },
  { name: "Athens", country: "GR", continent: "Europe" },
  { name: "Prague", country: "CZ", continent: "Europe" },
  { name: "Bucharest", country: "RO", continent: "Europe" },
  { name: "Hamburg", country: "DE", continent: "Europe" },
  // North America
  { name: "New York", country: "US", continent: "North America" },
  { name: "Los Angeles", country: "US", continent: "North America" },
  { name: "Mexico City", country: "MX", continent: "North America" },
  { name: "Toronto", country: "CA", continent: "North America" },
  { name: "Chicago", country: "US", continent: "North America" },
  { name: "Houston", country: "US", continent: "North America" },
  { name: "Montreal", country: "CA", continent: "North America" },
  { name: "Dallas", country: "US", continent: "North America" },
  { name: "Miami", country: "US", continent: "North America" },
  { name: "San Francisco", country: "US", continent: "North America" },
  { name: "Philadelphia", country: "US", continent: "North America" },
  { name: "Atlanta", country: "US", continent: "North America" },
  { name: "Vancouver", country: "CA", continent: "North America" },
  // South America
  { name: "São Paulo", country: "BR", continent: "South America" },
  { name: "Buenos Aires", country: "AR", continent: "South America" },
  { name: "Rio de Janeiro", country: "BR", continent: "South America" },
  { name: "Lima", country: "PE", continent: "South America" },
  { name: "Bogotá", country: "CO", continent: "South America" },
  { name: "Santiago", country: "CL", continent: "South America" },
  { name: "Caracas", country: "VE", continent: "South America" },
  { name: "Belo Horizonte", country: "BR", continent: "South America" },
  { name: "Porto Alegre", country: "BR", continent: "South America" },
  { name: "Montevideo", country: "UY", continent: "South America" },
  { name: "Quito", country: "EC", continent: "South America" },
  { name: "Guayaquil", country: "EC", continent: "South America" },
  { name: "Medellín", country: "CO", continent: "South America" },
  // Oceania
  { name: "Sydney", country: "AU", continent: "Oceania" },
  { name: "Melbourne", country: "AU", continent: "Oceania" },
  { name: "Auckland", country: "NZ", continent: "Oceania" },
  { name: "Brisbane", country: "AU", continent: "Oceania" },
  { name: "Perth", country: "AU", continent: "Oceania" },
  { name: "Wellington", country: "NZ", continent: "Oceania" },
  { name: "Adelaide", country: "AU", continent: "Oceania" },
  { name: "Canberra", country: "AU", continent: "Oceania" },
  { name: "Christchurch", country: "NZ", continent: "Oceania" },
  { name: "Gold Coast", country: "AU", continent: "Oceania" },
  { name: "Hobart", country: "AU", continent: "Oceania" },
];

export default TOP_CITIES; 